### PR TITLE
lib: better support for self-hosted instances

### PR DESCRIPTION
**Pull request by fsouza**
This change removes some instances of the hardcoded string `https://sourcegraph.com`, and relies on the environment variable `SRC_ENDPOINT`.

Additionally, it also makes some changes to how environment variables are handled to make sure it matches the instructions in the src-cli README, namely:

1. the environment variable for the token is `SRC_ACCESS_TOKEN`, not `SOURCEGRAPH_ACCESS_TOKEN`
2. the endpoint isn't guaranteed to have a trailing `/` (and the instructions in the README of src-cli don't mention it)

I don't feel strongly about those, but it's just something I noticed while trying to follow the instructions in the README. If we don't want to keep those, it may be worth it mentioning that a trailing slash is required and that the environment variable for the access token is different.

I haven't added any tests just yet, because I want to see what kind of feedback this will get before investing in tests.

In general, I haven't been able to get it to work yet, but at this point it's because some of the queries checked in here don't work with the instance I have at work (probably a versioning thing). I'll keep digging and thinking about how we can handle such differences.

Related to #11.

### CODE REVIEW

**Comment by rmagatti** [comment]
Hey @fsouza, while testing this branch out with a company-internal sourcegraph instance I'm getting some errors on the rust side. I apologize in advance for the formatting of the error, and for the fact that it is a screenshot in the first place but this is the best I could get for now 😄 

Screenshot 2023-02-21 at 11 56 03 PM

**Comment by fsouza** [comment]
@rmagatti it sounds like it's failing to parse the response. At my job, we have the API running at a different hostname from the web, you may be in a similar situation. 

For example, let's say your web instance is running at https://sourcegraph.example.com, but the API is listening on https://sourcegraph-api.example.com/, you'd need to make sure you pass https://sourcegraph-api.example.com to sg.nvim. Something like:

```lua
vim.api.nvim_create_autocmd("BufReadCmd", {
  group = "sg.nvim",
  pattern = { "https://sourcegraph.example.com/*" }, 
  callback = function(args)
    local sg = require("sg")
    local match = string.gsub(args.match, "://sourcegraph.", "://sourcegraph-api.")

    sg.bufread(match)
  end,
})
```

Not sure what else can it be. Perhaps you can run some sort of proxy in the middle to intercept the request and the response and see what's going on?

**Comment by rmagatti** [comment]
So I'm not sure that's it. I added some `println` statements to the rust code and it looks to me like it's entering the error clause when making the graphql request, which suggests to me that it's not that it's unable to parse the request, but that the request it merely unsuccessful in the first place. Though I can't seem to get a good log from it...

```rust
    pub async fn get_graphql<Q: GraphQLQuery>(variables: Q::Variables) -> Result<Q::ResponseData> {
        println!("GRAPHQL_ENDPOINT: {:?}", GRAPHQL_ENDPOINT.to_string());

        let response =
            match post_graphql::<Q, _>(&CLIENT, GRAPHQL_ENDPOINT.to_string(), variables).await {
                Ok(response) => response,
                Err(err) => {
                    println!("err: {:?}", err);

                    return Err(anyhow::anyhow!(
                        "Failed with status: {:?} || {err:?}",
                        err.status()
                    ))
                }
            };

        response.data.context("get_graphql -> data")
    }
```

Disclaimer: this is pretty much my first time reading, much less writing any rust, so bear 🐻 with me

**Comment by fsouza** [comment]
Oh yeah, that's kind of what I meant. Failing to parse because the response may not be valid GraphQL (sorry, it was late when I wrote the previous message).

Are you able to use the `src` CLI pointing to the endpoint that you configured neovim with?

**Comment by rmagatti** [comment]
Yes, indeed I am, calling `src api -query='query { currentUser { username } repositories(first: 10) { nodes { name } } }'` returns the expected data correctly

**Comment by fsouza** [comment]
@rmagatti gotcha, it could be that you're running in the same issues I ran into (in my case, the queries in https://github.com/tjdevries/sg.nvim/tree/master/gql are not compatible with the version of sourcegraph running at work)

**Comment by rmagatti** [comment]
Right, I suppose that would make sense. How could I verify that is the case?

**Comment by fsouza** [comment]
> Right, I suppose that would make sense. How could I verify that is the case?

iirc I tested the [PathInfo query](https://github.com/tjdevries/sg.nvim/blob/master/gql/path_info_query.graphql) using the GraphQL explorer and it didn't work, it said that type didn't exist, which makes me think it's a version mismatch. I haven't had much time recently, but my next plan was to try to figure out alternatives for all queries (if possible), and then see how I could customize it (may require forking since the queries get embedded in the compiled binary).

**Comment by rmagatti** [comment]
What came to mind was if queries could be done by simply calling to the `src` cli instead of directly. 🤔

**Comment by fsouza** [comment]
> What came to mind was if queries could be done by simply calling to the `src` cli instead of directly. 🤔

Oh yeah that should work too. With `src api`. I just tested, and this is what I get:

```
％ src api 'name=some/repo' 'revision=HEAD' 'path=file-path' < gql/path_info_query.graphql
{
  "errors": [
    {
      "locations": [
        {
          "column": 7,
          "line": 6
        }
      ],
      "message": "Cannot query field \"path\" on type \"GitCommit\"."
    },
    {
      "locations": [
        {
          "column": 9,
          "line": 8
        }
      ],
      "message": "Fragment cannot be spread here as objects of type %!q(\u003cnil\u003e) can never be of type \"GitBlob\"."
    },
    {
      "locations": [
        {
          "column": 9,
          "line": 12
        }
      ],
      "message": "Fragment cannot be spread here as objects of type %!q(\u003cnil\u003e) can never be of type \"GitTree\"."
    }
  ]
}
```

The browser UI/explorer is helpful to "fix" the query though, as it will have schema documentation.

**Comment by tjdevries** [comment]
What versions of sourcegraph are you both running? (if you can say)

**Comment by tjdevries** [comment]
I just pushed a change that incorporated some of the changes here, if you wanna test out HEAD right now, it might solve your problems?... not sure :) hoping it does though haha

**Comment by rmagatti** [comment]
> What versions of sourcegraph are you both running? (if you can say)

I'm on 4.5.1.

Also, it works now in HEAD 🎉 

hhgf

**Comment by tjdevries** [comment]
AWESOME! I'll close this for now then -- Please report any issues you find as you're using it. I have time set aside this quarter to work on this more :)

**Pull request closed without merging**
