### PR TITLE
fix: nix build instructions

### LINKED ISSUE #138: Fix nix build instructions
@willruggiano / @Pegasust 

Do either of you have any thoughts about how to update the nix stuff? I don't think any of it's working but I've also stopped completely changing how we build/setup the environment now. So if you have some thoughts about what could be done I'd love to hear them (otherwise I may try and track it down myself or might just have to remove the nix stuff entirely cause I don't have a good way to test / setup at the moment for it)

Thanks :)

### PR DESCRIPTION
**Pull request by willruggiano**
Closes #138

### CODE REVIEW

**Comment by willruggiano** [comment]
Can you enable the Nix github workflow to see if the build works on macOS? I don't have a macOS machine readily available :/

**Comment by willruggiano** [comment]
Updated the github workflow and README/NixOS instructions as well.

**Comment by willruggiano** [comment]
> Approved the workflows, thanks a bunch (i have literally no idea what's happening)

Honestly I didn't either :eyes:

**Comment by tjdevries** [comment]
I think we can ignore the e2e tests -- it's because it's being run on a fork and we have some special auth stuff that only runs here.

**Comment by willruggiano** [comment]
Good lord these Nix workflows take forever! :(

**Comment by willruggiano** [comment]
Welp, 26m 41s later looks like macOS is good to go hahahah

Want me to disable the nix workflow?

**Comment by tjdevries** [comment]
Yeah, let's disable them - i don't want to wait and waste 30 min of build time every time we have a commit haha

**Comment by tjdevries** [comment]
and then we can merge. ty for the help

**Comment by willruggiano** [comment]
Disabled, except for PRs to the nix files themselves. Thought that seemed reasonable :)

**Comment by tjdevries** [comment]
Wonderful, thanks!

**Pull request merged**
