### PR TITLE
Nixify

### PR DESCRIPTION
**Pull request by willruggiano**
Not sure if you want Nix-specific stuff in your repo, some people do, others don't. Regardless, thought I'd open the PR. I'm happy to maintain the Nix stuff in my own fork... I'm probably the only one using sg-nvim _and_ Nix/OS together :P

The only non-Nix related change is to check for sg-lsp in PATH before using the local build artifacts.

### CODE REVIEW

**Comment by tjdevries** [comment]
if i update any dependencies in cargo.toml or anywhere else, do I have to do anything to update these nix files?

**Comment by willruggiano** [comment]
> if i update any dependencies in cargo.toml or anywhere else, do I have to do anything to update these nix files?

No, the nix stuff is just a wrapper on top of Cargo so any normal cargo stuff will force a rebuild for e.g. me, downstream consumer, but won't require additional nix-specific code changes on your part

**Comment by tjdevries** [comment]
was closing this on accident?

**Comment by tjdevries** [comment]
This good to merge? Can you add a note in the README about this if there is anything future users need to do (or just make a note that no one needs to run anything to update the flake.lock or whatever)

**Comment by willruggiano** [comment]
Sure

**Comment by willruggiano** [comment]
Done.

**Comment by tjdevries** [comment]
Thanks <3

**Pull request merged**
