### PR TITLE
nix: add OPENSSL_NO_VENDOR env to cargo build process

### PR DESCRIPTION
**Pull request by dechnik**
after recent changes nix build started failing, this fixes the issue

### CODE REVIEW

**Comment by tjdevries** [comment]
Hmm @dechnik it fails for the macos one. Any guess why?

**Comment by dechnik** [comment]
Ok i see it is more complex issue, it does not build for aarch64-linux neither. Something with recent linker options, i will investigate more.

**Comment by tjdevries** [comment]
We can merge this one if it fixes the immediate problem for you and then investigate part 2 if you want

**Comment by dechnik** [comment]
with  https://github.com/sourcegraph/sg.nvim/pull/159/commits/2260f529c498565d1dd8ea0840fb8cd8b8539c75 change darwin system should build as before

**Comment by dechnik** [comment]
hmm same error, so this must be this linker issue

**Comment by tjdevries** [comment]
I don't know if it is possible to have Nix choose different crate features somehow?... the main problem must be the changes I made to the crate feature to try and vendor openssl into the binary because people didn't have the headers on certain OS's

**Comment by dechnik** [comment]
ok build works for aarch64-linux, possible fix for darwin also included

**Comment by tjdevries** [comment]
Thanks!

**Pull request merged**
